name: shady
description: Making it easier to work with GLSL shaders in Flutter.

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  vector_math: ^2.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
